<a href="https://colab.research.google.com/github/AMANVISHWAKARMA27/Redemption-2024/blob/prediction.csv/Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [33]:
df = pd.read_csv("prediction.csv")
df

Unnamed: 0  area        prices
0            0  1000  3.164041e+05
1            1  1500  3.842979e+05
2            2  2300  4.929281e+05
3            3  3540  6.613048e+05
4            4  4120  7.400616e+05
5            5  4560  7.998082e+05
6            6  5490  9.260908e+05
7            7  3460  6.504418e+05
8            8  4750  8.256079e+05
9            9  2300  4.929281e+05
10          10  9000  1.402705e+06
11          11  8600  1.348390e+06
12          12  7100  1.144709e+06

In [34]:
df.rename(columns={'Unnamed: 0': 'Index'}, inplace=True)
# assigning a name to the first column.
df

Index  area        prices
0       0  1000  3.164041e+05
1       1  1500  3.842979e+05
2       2  2300  4.929281e+05
3       3  3540  6.613048e+05
4       4  4120  7.400616e+05
5       5  4560  7.998082e+05
6       6  5490  9.260908e+05
7       7  3460  6.504418e+05
8       8  4750  8.256079e+05
9       9  2300  4.929281e+05
10     10  9000  1.402705e+06
11     11  8600  1.348390e+06
12     12  7100  1.144709e+06

In [35]:
reg = linear_model.LinearRegression()
reg.fit(df[['area']], df.prices)

LinearRegression()

In [36]:
x = 50
y = reg.predict([[x]])
y
# prediction for input 1

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([187405.82191781])

In [37]:
# Loss finction value for input 1
lf = abs(y - x)
lf

array([187355.82191781])

In [38]:
x = 658
y = reg.predict([[x]])
y
# prediction for input 2

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([269964.7260274])

In [39]:
# Loss finction value for input 2
lf = abs(y - x)
lf

array([269306.7260274])

In [40]:
x = 34
y = reg.predict([[x]])
y
# prediction for input 3

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([185233.21917808])

In [41]:
# Loss finction value for input 3
lf = abs(y - x)
lf

array([185199.21917808])